flags: {}
packages:
- '.'

# The 'irc' extra-dep is only necessary for building with any
# snapshots before nightly-2015-08-25.
#
# 'irc-ctcp' and 'irc-conduit' have been submitted for inclusion into
# Stackage.
extra-deps:
- irc-0.6.1.0
- irc-conduit-0.1.1.2
- irc-ctcp-0.1.2.1

resolver: lts-4.2
